# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Análisis de la compra de leche"

# Logo image
image: 

#Description of your site
description: >-
  

# URL of your contracts file or API endpoint
contracts_url: "/assets/data/contracts.json"

# URL of your beneficial ownership file or API endpoint
bods_url: ""

graph:
  # The name of your graphic
  - title: "Visualización de compra de la Leche"
  # los tamaños minimos y maximos de los nodos (en pixeles, aproximativo)
  - sizes:
    - min: 10
    - max: 300
  # colores de nodos y connectores
  - colours:
      - nodes:
          - default: '#1ee6d3'
          - contract: '#1ee6d3'
          - contractTypes: '#3abdc3'
          - contractByType: '#438a9c'
          - organization: '#3c5a6f'
          - shareholderPerson: '#EB639A'
      - links:
          - default: '#706F74'
          - contractsTypes: '#706F74'
          - toCenter: '#706F74'
          - toContractType: '#706F74'
          - toOrganization: '#706F74'
# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - docs/

# Collections
collections_dir: collections
collections:
  first-slider:
    output: true
  visualization-slider:
    output: true

# Set to false to hide excerpts on the posts page
show_excerpts: true
future: true
